---
- name: Configurar IPv6 en Loopback 33
  hosts: routers
  gather_facts: false

  tasks:
    - name: Asignar IPv6 global y link-local a Loopback 33
      ios_config:
        parents: "interface Loopback33"
        lines:
          - description IPv6 ADDRESS
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local

    - name: Mostrar el comando show ipv6 interface brief
      ios_command:
        commands:
         - show ipv6 interface brief
      register: output
